### ISSUE TITLE
improve format performance

### ISSUE THREAD

**Issue by enverbisevac** [VauntDev/tqla#22]
I think regexp.Compile can be placed outside of format function, so we dont need every time to compile. https://github.com/VauntDev/tqla/blob/c4ff8cdb2d10ac3e43b272e76dbd39f7cffa75e3/placeholder.go#L82 

```
var whitespaceRegex := regexp.MustCompile(`\s+`)
```

this will be initialized only once.

**Comment by elewis787** [comment]
Good call out! Thank you. Will work on getting this included.

**Comment by elewis787** [comment]
Addressed in #23
