### ISSUE TITLE
Postgres db driver examples

### ISSUE THREAD

**Issue by elewis787** [VauntDev/tqla#5]
We currently only show an example for SQLite. 

It would be great to build out the example set to include postgres 

Some of SQL drivers may require code changes ( see #3 for spanner support )

**Comment by MinhDuongg** [comment]
Is this issue still open ? Can I take care of this issue?

**Comment by elewis787** [comment]
It is still open! Feel free to work on it. 

There is a sqlite example you are welcome to use as reference - https://github.com/VauntDev/tqla/blob/main/example/main.go 

I think we would work on adding a folder structure for each db type 

i.e 

```
example/sqlite
              / postgres
```

**Comment by elewis787** [comment]
Closed by #10
