### ISSUE TITLE
Mysql db driver example 

### ISSUE THREAD

**Issue by elewis787** [VauntDev/tqla#7]
We currently only show an example for SQLite.

It would be great to build out the example set to include Mysql

Some SQL drivers may require code changes ( see https://github.com/VauntDev/tqla/issues/3 for spanner support )

**Comment by Unagi-zoso** [comment]
Could you assign this issue to me?

**Comment by elewis787** [comment]
@Unagi-zoso assigned to you! Please reach out if you have questions.

**Comment by elewis787** [comment]
Fixed in #24
